[phases.setup]
aptPkgs = [
  "build-essential", 
  "python3-dev", 
  "libpq-dev", 
  "libffi-dev", 
  "libjpeg-dev", 
  "libglib2.0-0", 
  "libnss3", 
  "libnspr4", 
  "libatk1.0-0", 
  "libatk-bridge2.0-0", 
  "libcups2", 
  "libdrm2", 
  "libdbus-1-3", 
  "libxcb1", 
  "libxkbcommon0", 
  "libx11-6", 
  "libxcomposite1", 
  "libxdamage1", 
  "libxext6", 
  "libxfixes3", 
  "libxrandr2", 
  "libgbm1", 
  "libpango-1.0-0", 
  "libcairo2", 
  "libasound2"
]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.setup.env]
PYTHONUNBUFFERED = "1"

[start]
cmd = "playwright install && streamlit run app.py --server.port=$PORT --server.address=0.0.0.0"