[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath = "/_stcore/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[env]
PORT = "8501"
PLAYWRIGHT_BROWSERS_PATH = "/ms-playwright"
PYTHONUNBUFFERED = "1"
STREAMLIT_APP = "debug_app.py"  # Alterar para usar o app de diagnóstico