[build]
builder = "NIXPACKS"
buildCommand = "echo building..."

[deploy]
startCommand = "bash startup.sh"
healthcheckPath = "/"
healthcheckTimeout = 600
healthcheckInterval = 30
healthcheckPort = 8000
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10